Repository linkerd/website, pull requests merged in 2019-08, with the labels that each got.

#450 Introduce a Securing Your Cluster page, tap
  linkerd.io/content/2/tasks/securing-your-cluster.md
  linkerd.io/static/tap-rbac/index.html
Labels: docs

#471 Update Tap RBAC page for 2.5.0, dashboard support
  linkerd.io/content/2/tasks/securing-your-cluster.md
Labels: docs, priority/P0

#463 Task 'Generating certificates for Linkerd identity'
  linkerd.io/content/2/tasks/generate-certificates.md
Labels: docs, priority/P0

#465 Add Helm install instructions
  linkerd.io/content/2/tasks/install-helm.md
Labels: docs, priority/P0

#469 Bumping edge version to 19.8.4
  Makefile
Labels: priority/P0

#474 Bumping edge version to 19.8.5
  Makefile
Labels: priority/P0

#470 Update website for stable-2.5.0 release
  Makefile
  linkerd.io/content/2/tasks/books.md
  linkerd.io/content/2/tasks/upgrade.md
  linkerd.io/content/blog/service-profiles-for-per-route-metrics.md
  linkerd.io/content/dashboard/announcing-linkerd-stable-2-5-0.md
  linkerd.io/data/cli.yaml
Labels: docs, priority/P0

#475 initial draft of 2.5 announcement blog post
  linkerd.io/content/_index.md
  linkerd.io/content/blog/_index.md
  linkerd.io/content/blog/announcing-linkerd-2-5.md
  linkerd.io/static/uploads/diving-helmet.jpg
Labels: priority/P0
