Repository linkerd/website, pull requests merged in 2019-02, with the labels that each got.

#123 Fix spelling on linkerd check link
  linkerd.io/content/2/faq/_index.md
Labels: bug, docs

#135 Add service profile and related docs
  linkerd.io/content/2/cli/routes.mmark
  linkerd.io/content/2/cni/_index.md
  linkerd.io/content/2/edge/_index.md
  linkerd.io/content/2/get-involved/_index.md
  linkerd.io/content/2/ha/_index.md
  linkerd.io/content/2/proxy-injection/_index.md
  linkerd.io/content/2/retries-and-timeouts/_index.md
  linkerd.io/content/2/service-profiles/_index.md
Labels: area/arch, area/tutorial, docs, priority/P0

#156 Add upgrade guide for 2.1 -> 2.2
  linkerd.io/content/2/upgrade/_index.md
  linkerd.io/data/cli.yaml
Labels: area/upgrade, docs, priority/P0
