Repository linkerd/website, pull requests merged in 2019-07, with the labels that each got.

#387 Add docs for multi stage installation
  linkerd.io/content/2/getting-started/_index.md
  linkerd.io/content/2/tasks/install.md
  linkerd.io/content/2/tasks/uninstall.md
  linkerd.io/content/2/tasks/upgrade.md
Labels: docs

#388 Update the CLI and annotation docs for 2.4
  linkerd.io/content/2/reference/cli/check.md
  linkerd.io/content/2/reference/cli/install.md
  linkerd.io/content/2/reference/cli/upgrade.md
  linkerd.io/data/cli.yaml
  linkerd.io/layouts/partials/cli/annotations.html
  linkerd.io/layouts/shortcodes/cli.html
  linkerd.io/layouts/shortcodes/cli/examples.html
  linkerd.io/layouts/shortcodes/cli/flags.html
Labels: docs

#389 Update Troubleshooting page with new 2.4 checks
  linkerd.io/content/2/tasks/troubleshooting.md
Labels: area/troubleshooting, docs

#392 Add PSP doc
  linkerd.io/content/2/tasks/using-psp.md
Labels: docs, priority/P0

#367 2.4 - Bump the supported k8s version to 1.12
  linkerd.io/content/2/tasks/troubleshooting.md
Labels: area/check

#405 Add troubleshooting section for NET_RAW check
  linkerd.io/content/2/tasks/troubleshooting.md
Labels: area/check
